[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GCPDecompositions = "f59fb95b-1bc8-443b-b347-5e445a549f37"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[compat]
BenchmarkTools = "1.3.2"
GCPDecompositions = "0.1.2"
PkgBenchmark = "0.2.12"
